users:
  - default
  - name: ansible
    gecos: ansible
    primary_group: ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtONBRZZb3Ot5KXGZtNT6OE5/FYs2tCZV3KmaMYk4bDTjZEBmPJYz3Py39JnR8P+UHDF0H+VHDK+I3CE5c3hUEFqBBh2ICEAndx4A3GVtdClfkHqgPMlb8tjjfV5rRO5rT8ukbPZfl1VUpQEvt4grxvzRjoTToV3MGLQ9VvYevI6vmwcai2ss9/8ZHMjQrTShCiZVjObEDASABxDm9CvlKUQbAgfMgXd0JsQw/h/PqinSn02gBQ5f8vTjxU/6Lm+sJbvhgkQBFhVv2fkpkTCGqT0n4tBWLv8vg9jpiNFhfv5YJFcEvyDzafIBsxLejCHnoqGYrAwxjnkcQnWmB6npPek4uCtrCj/XKPBvTPXQoA3nktgHlvyt9tm+gpZ4/WcFR+gwI+kWNQRBg43E7yNLk7rjMFSZwKXSq6+c4t4GX4dL0jbr4TOsDza/rjnKnqd+P9TFBl5bJqRCnuh+EXkUrJS8nSz4/f2m2spkt16AOmxE9ReLkeJJvRnGRiF5OjyE= student@fhm12iutaehd83piugpu
