stages:
  - module-pipelines

deploy-helm-chart:
  stage: module-pipelines
  trigger:
    include:
      - "/kubernetes/sausage-store-chart/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:  # как только происходит изменение в папке backend, запускается дочерний пайплайн, который лежит в этой папке
      - kubernetes/sausage-store-chart/**/*