stages:
  - module-pipelines

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/kubernetes/backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:  # как только происходит изменение в папке backend, запускается дочерний пайплайн, который лежит в этой папке
      - /kubernetes/backend/**/*

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/kubernetes/frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:  # как только происходит изменение в папке backend, запускается дочерний пайплайн, который лежит в этой папке
      - /kubernetes/frontend/**/*