---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.metadata.name }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
