stages:
  - deploy

deploy-k8s-backend:
  stage: deploy
  image: bitnami/kubectl:1.30.3
  environment:
    name: production/backend
  script:
    - mkdir -p ~/.kube
    #- echo -n "$KUBECONFIG" | base64 > ~/.kube/config
    #- cat ~/.kube/config 
    - chmod 600 ~/.kube/config
    - kubectl apply -f kubernetes/backend/secrets.yaml
    - rm -f ~/.kube/config