stages:
  - deploy

deploy-k8s-backend:
  stage: deploy
  image: bitnami/kubectl:1.30.3
  environment:
    name: production/backend
  script:
    - mkdir -p ~/.kube
    - cat kubernetes/config | base64 -d > ~/.kube/config 
    - chmod 600 ~/.kube/config
    - kubectl apply -f kubernetes/backend/secrets.yaml
    - kubectl apply -f kubernetes/backend/deployment.yaml
    - kubectl apply -f kubernetes/backend/service.yaml
    - rm -f ~/.kube/config