# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLmJia0hqSUVCQTlmdTZZcTYyUzdRYlVXRAo=
type: Opaque

# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLmJia0hqSUVCQTlmdTZZcTYyUzdRYlVXRAo=
type: Opaque
# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:

---
kind: Secret
apiVersion: v1
metadata:
  name: psql-secret
data:
  psql-user: c3RkLWV4dC0wMDYtMTA=
  psql-password: VGVzdHVzcjEyMzQ=
type: Opaque

---
apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMV1Y0ZEMwd01EWXRNVEE2T0hkNFlWVTNZVmszTWxKaVNsZDNNM2xCZWs0PSIKCQl9Cgl9Cn0K
metadata:
  name: docker-config-secret
type: kubernetes.io/dockerconfigjson
