stages:
  - deploy

deploy-frontend:
  stage: deploy
  image: bitnami/kubectl:1.30.3
  environment:
    name: production/frontend
  before_script:
    - apk add docker-cli-compose openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp -r ./frontend ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/kuber/frontend
    - ssh ${DEV_USER}@${DEV_HOST};
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - kubectl apply -f backend