---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      
      location /api {
        proxy_pass http://backend:8080;
      }
      
      location / {
        root /app/frontend;
        index index.html;
      }

    }
