stages:
  - deploy

deploy-k8s-backend-report:
  stage: deploy
  image: bitnami/kubectl:1.30.3
  environment:
    name: production/frontend
  script:
    - mkdir -p ~/.kube
    - cat kubernetes/config | base64 -d > ~/.kube/config 
    - chmod 600 ~/.kube/config
    - kubectl apply -f kubernetes/backend-report/secrets.yaml
    - kubectl apply -f kubernetes/backend-report/deployment.yaml
    - kubectl apply -f kubernetes/backend-report/service.yaml
    - rm -f ~/.kube/config