---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMV1Y0ZEMwd01EWXRNVEE2T0hkNFlWVTNZVmszTWxKaVNsZDNNM2xCZWs0PSIKCQl9Cgl9Cn0K
kind: Secret
metadata:
  name: docker-config-secret
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLmJia0hqSUVCQTlmdTZZcTYyUzdRYlVXRAo=
type: Opaque